spring.application.name=proyecto-jpa

spring.jpa.database-platform=org.hibernate.dialect.H2Dialect
spring.datasource.url=jdbc:h2:./proyecto-jpa
spring.datasource.driverClassName=org.h2.Driver
spring.datasource.username=sa
spring.datasource.password=sa

# Cambiado de 'none' a 'update' para que Hibernate procese las entidades
spring.jpa.hibernate.ddl-auto=create

spring.jpa.show-sql=true
spring.jpa.properties.hibernate.format_sql=true

spring.jpa.properties.jakarta.persistence.schema-generation.scripts.action=create
spring.jpa.properties.jakarta.persistence.schema-generation.database.action=create

# Cambiado de 'target/nuevo-esquema.sql' a 'nuevo-esquema.sql' para que sea visible nada mas abrir el proyecto
spring.jpa.properties.jakarta.persistence.schema-generation.scripts.create-target=nuevo-esquema.sql

jwt.secret=desarrollodeaplicacionesweb20252026desarrollodeaplicacionesweb20252026